### ISSUE TITLE
Chat example should be updated to current Flutter version

### ISSUE THREAD

**Issue by DavidMihola** [google/flutter_flux#12]
Which means moving to new Gradle build as well as some changes in the Flutter API itself (`ListTile` instead of `ListItem`, `ListView` instead of `Block`, etc.).

I've already done so locally and got the app running with today's Flutter version. I can also submit a pull request, but should I put the updated example in a new folder or just overwrite `example/chap_app`?

**Comment by Hixie** [comment]
You should submit a pull request! That would be great.

cc @jimbeveridge

**Comment by jimbeveridge** [comment]
You can overwrite chat_app. Thanks!

**Comment by DavidMihola** [comment]
Great - I'll send the PR this weekend!

**Comment by Brahmasmi** [comment]
@DavidMihola I suppose that @rxlabz's updates in #14 have addressed the concerns raised here. @Hixie Perhaps we need to close this.
