### ISSUE TITLE
flutter_flux is out of date

### ISSUE THREAD

**Issue by eseidelGoogle** [google/flutter_flux#13]
We should either bring it up to date (reported by @harveynick), or remove it from the Flutter organization.

@Hixie @jimbeveridge

**Comment by eseidelGoogle** [comment]
This may also just be perception and is caused by: https://github.com/flutter/flutter_flux/pull/10 and https://github.com/flutter/flutter_flux/issues/12

@Hixie unless you or @abarth object, I recommend we remove this from the flutter org and leave it accessible under @jimbeveridge's github.

**Comment by sethladd** [comment]
sgtm

**Comment by rxlabz** [comment]
I don't know if you want to keep this package here, but PR #14 updates the package and the example.

**Comment by Brahmasmi** [comment]
I would prefer we rather keep this. Considering there is a dearth of proper architecture guidance, having this will atleast give some direction to volks.

Can we close this issue? Especially as @rxlabz seems to have closed the gap with #14. Let us open a new issue to track the chore of keeping the example updated with the new Flutter releases.

Also, danke @rxlabz for the update.

**Comment by kentcb** [comment]
I'm a bit confused, no doubt partly because I'm new to both the Dart and flutter ecosystems.

I see #14 has been merged, but the latest release of `flutter_flux` (`4.0.1`) was released _before_ that merge. What is the best way to ensure I'm using the latest version of this library?

**Comment by jimbeveridge** [comment]
Sorry about the version confusion. Updated version to 4.1 in 8595064cf5d8ad5e638984e0be385866f0ca0cb5.
