### ISSUE TITLE
Will this be maintained?

### ISSUE THREAD

**Issue by TobiPristupin** [google/flutter_flux#21]
I'd really like to use this library for flutter. Will it be maintained over time or is it just experimental?
Thanks for your hard work.

**Comment by miguelcaravantes** [comment]
Same question

**Comment by jimbeveridge** [comment]
I maintain this library on a time-available basis, so it's not updated in lock-step with Flutter. Although there have been periods of breakage in the past, this should improve now that Flutter has gone into beta.

**Comment by jimbeveridge** [comment]
Updated version to 4.1 in 8595064cf5d8ad5e638984e0be385866f0ca0cb5. This update is compatible with the Flutter beta.
