### ISSUE TITLE
Wrong flutter_flux code when pulled down from Dart package

### ISSUE THREAD

**Issue by jonjon1123** [google/flutter_flux#22]
Hey all, trying out flutter_flux in a project, but can't seem to get the correct flutter_flux source pulled down. I have defined `flutter_flux: 4.0.1` in my pubspec.yaml, but when I look at the Dart Packages in Android Studio the code is not correct when compared to the GitHub repo for flutter_flux 4.0.1. For example, here is a the `StoreWatcherMixin` signature from my local machine: `abstract class StoreWatcherMixin implements State<dynamic>` and here is the same on GitHub: `abstract class StoreWatcherMixin<T extends StatefulWidget> implements State<T>`. I have tried re-installing everything, clearing the cache, cleaning the project... I am out of idea. Any thoughts?

**Comment by jimbeveridge** [comment]
I forgot to bump the version in pubspec.yaml after the last update. Try manually doing a `git pull`.

**Comment by jimbeveridge** [comment]
Updated version to 4.1 in 8595064cf5d8ad5e638984e0be385866f0ca0cb5
