### ISSUE TITLE
Is it okay to update widget's store in action callback?

### ISSUE THREAD

**Issue by hvkale** [google/flutter_flux#29]
I am referring to the example provided in this repo.
https://github.com/google/flutter_flux/blob/master/example/lib/main.dart#L62

The `handleChatMessageStoreChanged` function is called with the Store parameter and from the example it looks like, the downcasted store is assigned to a local scoped store and not the widget's store directly.

Can that function be written as
``` dart
class ChatScreenState extends State<ChatScreen>
    with StoreWatcherMixin<ChatScreen> {
  // Never write to these stores directly. Use Actions.
  ChatMessageStore messageStore;
  // ...
  void handleChatMessageStoreChanged(Store store) {
    // ChatMessageStore messageStore = store; // instead of this local scoped store ...
    messageStore = store; // ... assign to widget's store
    if (messageStore.currentMessage.isEmpty) {
        msgController.clear();
    }
    setState(() {});
  }
  // ...
}
```

If this is not okay, I would like to know why.

**Comment by jimbeveridge** [comment]
I believe that messageStore was already saved in the initState() function, so you don't need to reassign it. In any case, using the messageStore in the class is fine.

**Comment by hvkale** [comment]
Thanks for answer. What I am really wondering is if the new Store that comes in a callback has anything different than the one that belongs to the widget. I guess I can programmatically check that. Ideally it should be a singleton.

**Comment by jimbeveridge** [comment]
It's a good question and I spent some time tracing it through. The answer is that this should not happen *unless* you've set this function to be called in response to multiple stores changing. It's safer to use the parameter you're given because it would be a pretty painful bug to track down if someone makes a code change in the future that calls that function for an additional store.
