### ISSUE TITLE
Call setState inside StoreWatcher

### ISSUE THREAD

**Issue by trinhtuanvu** [google/flutter_flux#30]
Using StoreWatcher, how can I call setState() inside my custom handler?
```
class MyWidget extends StoreWatcher {
  @override
  void initStores(ListenToStore listenToStore) {
    listenToStore(storeToken, customHandleStoreChanged);
  }
  void customHandleStoreChanged(Store store) {
    // ...
    // setState(() {});
  }
}
```

**Comment by jimbeveridge** [comment]
I suggest you switch to StoreWatcherMixin as shown in the latest example. This should be a fairly straightforward change. StoreWatcherMixin is added to your State class and so will make calling setState() trivial.

The StoreWatcher class was intended to be a quick way to get started with flutter_flux, but it didn't work out as well as I'd hoped.

**Comment by trinhtuanvu** [comment]
Thanks for the answer. So the custom handler is not very useful and seems never be used.
