### ISSUE TITLE
Trigger on action with async functions does not trigger 

### ISSUE THREAD

**Issue by Panthro** [google/flutter_flux#33]
I have several triggerOnAction definitions in my store, and when I used `async` functions the store is never triggered.

Is this a working as designed or a bug?

If it is a bug I can setup a sample to demonstrate

**Comment by hvkale** [comment]
Would you mind sharing some code?

**Comment by Panthro** [comment]
Well, tried to but actually can't replicate.

Must be something strict in my setup, if I'm able to isolate and replicate I'll reopen.
