### ISSUE TITLE
triggerOnConditionalAction parameter type error

### ISSUE THREAD

**Issue by no-or-no** [google/flutter_flux#35]
in `store.dart`,
```dart
class Store {
    // ...
void triggerOnConditionalAction<T>(Action<T> action, bool onAction(T payload)) {
    assert(action != null);
    action.listen((dynamic payload) async {
      // Action functions must return bool, or a Future<bool>.
      dynamic result = onAction(payload);
      bool wasChanged;
      if (result is Future) {
        wasChanged = await result;
      } else {
        wasChanged = result;
      }
      if (wasChanged) {
        trigger();
      }
    });
  }
    // ...
}
```

the 2nd param `onAction` defined `bool` return type. it should be `dynamic`.

**Comment by AndreHaueisen** [comment]
@Amot-zpan , why `dynamic`?
The `bool` tells if `trigger()` should be called upon completion or not.

**Comment by no-or-no** [comment]
@AndreHaueisen ,
the method param `bool onAction(T payload)` return `bool` type definitely, so `dynamic result = onAction(payload);` is right, `bool` to `dynamic`. But the `result` is always `bool`, won't be `Future`.
if the `onAction()` is designed to support `async`, it should return `dynamic`, see also `void triggerOnAction<T>(Action<T> action, [dynamic onAction(T payload)])`

**Comment by gmcdowell** [comment]
Should the signature actually be a FutureOr<T> ??

e.g.

`void triggerOnConditionalAction<T>(Action<T> action, FutureOr<bool> onAction(T payload)) {`

**Comment by gmcdowell** [comment]
Have submitted a PR for suggested change
https://github.com/google/flutter_flux/pull/38
