### ISSUE TITLE
Outdated SDK version

### ISSUE THREAD

**Issue by AndreHaueisen** [google/flutter_flux#36]
I'm getting the following error:

`Because cronicalia_flutter depends on flutter_flux >=4.0.1 which requires SDK version >=1.19.0 <2.0.0, version solving failed.`

Could you update the pubspec.yaml?
Instead of 
```
environment:
  sdk: ">=1.24.0 <2.0.0"
```
use
```
environment:
  sdk: ">=1.24.0 <3.0.0"
```

**Comment by AndreHaueisen** [comment]
I created a PR to try to solve this issue

**Comment by jimbeveridge** [comment]
I've merged this PR. Thank you for your contribution!
