### ISSUE TITLE
StoreWatcherMixin can't be used as mixin because it extends a class other than Object

### ISSUE THREAD

**Issue by gmcdowell** [google/flutter_flux#40]
IDE: VSCode

Doesn't seem to preclude builds and debugging, however is triggering a heap of 'errors' in analyzer.

Thoughts?

`[✓] Flutter (Channel dev, v0.10.1, on Mac OS X 10.13.6 17G65, locale en-NZ)
    • Flutter version 0.10.1 at /Users/greg/Library/Developer/flutter
    • Framework revision 6a3ff018b1 (13 days ago), 2018-10-18 18:38:26 -0400
    • Engine revision 3860a43379
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/greg/Library/Android/sdk
    • Android NDK at /Users/greg/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[!] Connected device
    ! No devices available! Doctor found issues in 1 category.greg@iMac:~/Projects/Tierra/logmate_flutter$`

![screen shot 2018-11-01 at 17 41 34](https://user-images.githubusercontent.com/10100952/47833103-00397f80-ddfe-11e8-8df6-aecd01d280f4.png)

**Comment by jimbeveridge** [comment]
The warning is spurious. You need an `analysis_options.yaml` file to turn it off.

See https://github.com/google/flutter_flux/blob/master/analysis_options.yaml

**Comment by gmcdowell** [comment]
Thanks so much

**Comment by AndreHaueisen** [comment]
> The warning is spurious. You need an `analysis_options.yaml` file to turn it off.
> 
> See https://github.com/google/flutter_flux/blob/master/analysis_options.yaml

Where should I put this file?

**Comment by gmcdowell** [comment]
This file goes in your project root dir.

Unfortunately with the recent upgrade to Flutter/Dart this parameter has
been deprecated so no longer works :(

greg@iMac:~/Projects/Tierra/logmate_flutter$ flutter doctor --verbose
[✓] Flutter (Channel dev, v0.10.2, on Mac OS X 10.14.1 18B75, locale en-NZ)
    • Flutter version 0.10.2 at /Users/greg/Library/Developer/flutter
    • Framework revision d8cbb80206 (13 days ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/greg/Library/Android/sdk
    • Android NDK at /Users/greg/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[!] Connected device
    ! No devices available

**Comment by AndreHaueisen** [comment]
@gmcdowell I opened a PR that fixes the issue.
