### ISSUE TITLE
Pubspec.yaml is missing for chat_app

### ISSUE THREAD

**Issue by joeblew99** [google/flutter_flux#5]
Could you upgrade the instructions as i want to play around with this example...

env:
x-MacBook-Pro:chat_app apple$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /usr/local/flutter/flutter
    • Framework revision 16ce090fde (5 hours ago), 2016-11-01 20:34:36
    • Engine revision 63e71803de
    • Tools Dart version 1.21.0-dev.2.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-24, build-tools 24.0.3
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.1, Build version 8B62

[x] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/

[✓] Connected devices
    • None
x-MacBook-Pro:chat_app apple$ 

error:

````
x-MacBook-Pro:chat_app apple$ pwd
/Users/apple/workspace/go/src/github.com/flutter/flutter_flux/example/chat_app
x-MacBook-Pro:chat_app apple$ pub get
Could not find a file named "pubspec.yaml" in "/Users/apple/workspace/go/src/github.com/flutter/flutter_flux/example/chat_app".
x-MacBook-Pro:chat_app apple$ 

````

**Comment by joeblew99** [comment]
flutter packages get ???

**Comment by eseidelGoogle** [comment]
`flutter packages get` is just a simple wrapper around Dart's `pub get` which also sets the `FLUTTER_ROOT` environment variable to tell `pub` where to find the flutter sdk when resolving sdk-relative package paths.

@jimbeveridge probably has context on this example.

**Comment by jimbeveridge** [comment]
Thanks for your interest in flutter_flux!

Could you please do a `git pull` and make sure you are up to date? The `pubspec.yaml` file was missing in chat_app and I added it at the end of September. The latest revision from `git log` should say:

`Re-add example/chat_app/pubspec.yaml so flutter run works.`

To use this pubspec.yaml file, you'll need to use `flutter packages get`, then `flutter run` as Eric described. The `flutter` command should be on your path, as described in [Flutter Setup](https://flutter.io/setup/), under "Get the Flutter SDK".

There's also a Pull Request in flight for an updated README that might interest you:

https://github.com/jimbeveridge/flutter_flux/blob/fcdf5ff2ff567a3f0bced9d208a3896929b344e0/README.md

**Comment by yyoon** [comment]
@jimbeveridge Actually, I don't see your commit either, and `pubspec.yaml` file is missing in the chat example. Maybe it's only in your local repo somewhere?

**Comment by joeblew99** [comment]
@jimbeveridge thanks for FLutter :)

i am interesting in how much i can get out the Flux pattern. My plan is to ix it with an Event store and immutable types and se if i can get offline / online sync working with a backend that also is essentially an event store.

If you want it in a nutshell here it is:
http://tonsky.me/blog/the-web-after-tomorrow/

But, i am curious though whats going on with Flux because there are 2 implementation out there:
    - https://github.com/alexeieleusis/greencat
        - works in AngularDart & Flutter, with examples !
        - is 100% Dart. No Js dependency.
        - is being coached by a google and looks like its blessed.
    - https://github.com/flutter/flutter_flux
        - Only works with Flutter. 

If you have any info that would be great and feel free to chime in on the offline / online usage scenarios if you curious yourself.

**Comment by jimbeveridge** [comment]
@joeblew99 This repo implements Flux. The greencat repo implement Redux. Flux is based.

This repo has no .js dependency. Any reference to js is leftover from its original author, Workiva. Unlike greencat, we do not plan to make it work in both AngularDart and Flutter.

This Flux code has been tested with async events and works fine. The key is to implement the async event as an action. Do not add async code to the stores.

**Comment by joeblew99** [comment]
@jimbeveridge 

thanks for the explanation.
